package gov.iti.career.hub.persistence.entities.enums;

public enum Discipline {
    SOFTWARE_ENGINEERING_AND_DEVELOPMENT,
    CONTENT_DEVELOPMENT,
    INDUSTRIAL_SYSTEMS,
    INFORMATION_SYSTEMS,
    QA_ENGINEERING_AND_VALIDATION,
    INFRASTRUCTURE_NETWORK_AND_SECURITY_SERVICES
}
